sonar.projectKey=fhdamd-org_fhdamd-web
sonar.organization=fahadahmed

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/test/**,src/pages/**,src/layouts/**,src/content/**,src/content.config.ts,src/components/mdx/**,src/lib/**

sonar.cpd.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/content/site/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
