sonar.projectKey=fhdamd-org
sonar.organization=fahadahmed

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/test/**,src/pages/**,src/layouts/**,src/actions/**,src/firebase/**,src/server/**

sonar.cpd.exclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
