name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync docs to wiki
        run: |
          rsync -av --delete docs/ wiki/
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(docs): sync /docs to wiki" || echo "No changes to commit"
          git push
