name: Test Riqa

on:
  push:
    branches:
      - main
    paths:
      - apps/pdf-craft/**
      - packages/threads/**
  pull_request:
    paths:
      - apps/pdf-craft/**
      - packages/threads/**

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run tests with coverage
        run: pnpm --filter pdf-craft test:coverage

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838 # v3
        with:
          projectBaseDir: apps/pdf-craft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
